/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/


namespace Microsoft.Terminal.Settings
{
    interface ICoreSettings
    {
        UInt32 DefaultForeground { get; };
        UInt32 DefaultBackground { get; };
        UInt32 GetColorTableEntry(Int32 index);
        void SetColorTableEntry(Int32 index, UInt32 value);
        // TODO:MSFT:20642297 - define a sentinel for Infinite Scrollback
        Int32 HistorySize { get; };
        Int32 InitialRows { get; };
        Int32 InitialCols { get; };
        Boolean SnapOnInput { get; };
    };

}
