/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/

import "ITerminalConnection.idl";

namespace Microsoft.Terminal.TerminalConnection
{
    [default_interface]
    runtimeclass EchoConnection : ITerminalConnection
    {
        EchoConnection();
    };

}
