/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/

namespace TerminalComponent
{
    [default_interface]
    runtimeclass TerminalControl : Windows.UI.Xaml.Controls.UserControl
    {
        TerminalControl();
        void Prototype_WriteToOutput(String text);
        void Prototype_ChangeTextColors(UInt8 fgIndex, UInt8 bgIndex);
    }
}
