/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/

namespace Microsoft.Terminal.TerminalApp
{
    enum ShortcutAction
    {
        CopyText = 0,
        PasteText,
        NewTab,
        NewTabProfile0,
        NewTabProfile1,
        NewTabProfile2,
        NewTabProfile3,
        NewTabProfile4,
        NewTabProfile5,
        NewTabProfile6,
        NewTabProfile7,
        NewTabProfile8,
        NewTabProfile9,
        NewWindow,
        CloseWindow,
        CloseTab,
        SwitchToTab,
        NextTab,
        PrevTab,
        IncreaseFontSize,
        DecreaseFontSize
    };

    delegate void CopyTextEventArgs();
    delegate void PasteTextEventArgs();
    delegate void NewTabEventArgs();
    delegate void NewTabWithProfileEventArgs(Int32 profileIndex);
    delegate void NewWindowEventArgs();
    delegate void CloseWindowEventArgs();
    delegate void CloseTabEventArgs();
    delegate void SwitchToTabEventArgs();
    delegate void NextTabEventArgs();
    delegate void PrevTabEventArgs();
    delegate void IncreaseFontSizeEventArgs();
    delegate void DecreaseFontSizeEventArgs();

    [default_interface]
    runtimeclass AppKeyBindings : Microsoft.Terminal.TerminalControl.IKeyBindings
    {
        AppKeyBindings();

        void SetKeyBinding(ShortcutAction action, Microsoft.Terminal.TerminalControl.KeyChord chord);

        event CopyTextEventArgs CopyText;
        event PasteTextEventArgs PasteText;
        event NewTabEventArgs NewTab;
        event NewTabWithProfileEventArgs NewTabWithProfile;
        event NewWindowEventArgs NewWindow;
        event CloseWindowEventArgs CloseWindow;
        event CloseTabEventArgs CloseTab;
        event SwitchToTabEventArgs SwitchToTab;
        event NextTabEventArgs NextTab;
        event PrevTabEventArgs PrevTab;
        event IncreaseFontSizeEventArgs IncreaseFontSize;
        event DecreaseFontSizeEventArgs DecreaseFontSize;
    }
}
