/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/
import "IKeyBindings.idl";

namespace Microsoft.Terminal.TerminalControl
{
    // Class Description:
    // TerminalSettings encapsulates all settings that control the
    //      TermControl's behavior. In these settings there is both the entirety
    //      of the Core ITerminalSettings interface, and any additional settings
    //      for specifically the control.
    // The Core Terminal Settings are not defined in an idl this inherits from
    //      because that project is not a cppwinrt exposed project, only the control is.
    interface IControlSettings
    //requires Microsoft.Terminal.Core.ICoreSettings
    {
        Microsoft.Terminal.Core.ICoreSettings GetSettings();
        Boolean UseAcrylic;
        Double TintOpacity;

        String FontFace;
        Int32 FontSize;

        IKeyBindings KeyBindings;

        String Commandline;
        String WorkingDirectory;
        String EnvironmentVariables;

    };

}
