/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/

import "Microsoft.Terminal.TerminalControl.KeyChord.idl";

namespace Microsoft.Terminal.TerminalControl
{
    // [default_interface]
    interface IKeyBindings
    {
        Boolean TryKeyChord(KeyChord kc);
    }
}
