/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/
import "IKeyBindings.idl";

namespace TerminalControl
{
    // Class Description:
    // TerminalSettings encapsulates all settings that control the
    //      TermControl's behavior. In these settings there is both the entirety
    //      of the Core ITerminalSettings interface, and any additional settings
    //      for specifically the control.
    // The Core Terminal Settings are not defined in an idl this inherits from
    //      because that project is not a cppwinrt exposed project, only the control is.
    [default_interface]
    runtimeclass TerminalSettings
    {
        TerminalSettings();

        // --------------------------- Core Settings ---------------------------
        UInt32 DefaultForeground;
        UInt32 DefaultBackground;
        void GetColorTableEntry(Int32 index);
        void SetColorTableEntry(Int32 index, UInt32 value);
        Int32 HistorySize;
        Int32 InitialRows;
        Int32 InitialCols;
        Boolean SnapOnInput;
        // ------------------------ End of Core Settings -----------------------

        Boolean UseAcrylic;
        Double TintOpacity;

        String FontFace;
        Int32 FontSize;

        IKeyBindings KeyBindings;
    };

}
