namespace TerminalControl
{
    [default_interface]
    runtimeclass TermControl
    {
        TermControl();

        Windows.UI.Xaml.UIElement GetRoot();
        Windows.UI.Xaml.Controls.UserControl GetControl();
    }
}
