/********************************************************
 *                                                       *
 *   Copyright (C) Microsoft. All rights reserved.       *
 *                                                       *
 ********************************************************/

// import "Settings.idl";

namespace TerminalControl
{
    [default_interface]
    runtimeclass TerminalSettings
    {
        TerminalSettings();

        // --------------------------- Core Settings ---------------------------
        UInt32 DefaultForeground;
        UInt32 DefaultBackground;
        void GetColorTableEntry(Int32 index);
        void SetColorTableEntry(Int32 index, UInt32 value);
        Int32 HistorySize;
        Int32 InitialRows;
        Int32 InitialCols;
        // ------------------------ End of Core Settings -----------------------

        Boolean UseAcrylic;
        Double TintOpacity;

        String FontFace;
        Int32 FontSize;
    };

}
