import sys
import time # time.sleep is in seconds
from common import *

# $ python ~/vttests/name-of-file.py
if __name__ == '__main__':
    clear_all()
    print('This is the VT Test template.')

    write('Script started on 2019-01-02 12:36:53-0800')
    write('\n')
    write('')
    # write('\x1b]2;duhowett@DHOWETT-DEV:~\x07')
    write('\x1b[J(DHOWETT-DEV) ~ % ')
    write('\x1b[K')
    write('\x1b[?1h')
    write('\x1b=')
    write('\x1b[?2004h')
    write('s\x08screen -dRR irssi')
    write('\x1b[?1l')
    write('\x1b>')
    write('\x1b[?2004l')
    write('\n')
    write('')
    write('\n')
    write('')
    # write('\x1b]2;screen -dRR irssi\x07')
    write('\x1b[!p')
    write('\x1b[?3;4l')
    write('\x1b[4l')
    write('\x1b>')
    # write('\x1b[?1049h')
    write('\x1b[22;0;0t') # Save xterm icon and window title on stack.
    write('\x1b[4l')
    write('\x1b[?1h')
    write('\x1b=')
    write('\x1b(B')
    write('\x1b[1;30r')
    write('\x1b[H')
    write('\x1b[2J')
    # write('\x1b]0;irssi\x07')
    write('\x1b[H')
    write('\x1b[2J')
    write('\x1b[22;2t')
    # write('\x1b]2;irssi\x07 Irssi v1.0.5-1 - http://www.irssi.org')
    write('\n')
    write('12:35 -!-')
    write('\x1b[CEnd of WHOIS')
    write('\n')
    flush(1)
    write('12:36 Irssi commands:')
    write('\n')
    write('12:36 statusbar')
    write('\n')
    write('12:36 Name')
    write('\x1b[27CType   Placement Position Visible')
    write('\n')
    write('12:36 window')
    write('\x1b[25Cwindow bottom')
    write('\x1b[4C1')
    write('\x1b[8Cactive')
    write('\n')
    write('12:36 window_inact')
    write('\x1b[19Cwindow bottom')
    write('\x1b[4C1')
    write('\x1b[8Cinactive')
    write('\n')
    write('12:36 prompt')
    write('\x1b[25Croot   bottom')
    write('\x1b[4C100')
    write('\x1b[6Calways')
    write('\n')
    write('12:36 topic')
    write('\x1b[26Croot   top')
    write('\x1b[7C1')
    write('\x1b[8Calways')
    flush(1)
    write('\n')
    write('12:36 Statusbar: window')
    write('\n')
    write('12:36 Type')
    write('\x1b[5C: window')
    write('\n')
    write('12:36 Placement: bottom')
    write('\n')
    write('12:36 Position : 1')
    write('\n')
    write('12:36 Visible  : active')
    write('\n')
    flush(1)
    write('12:36 Items')
    write('\x1b[4C: Name')
    write('\x1b[32CPriority  Alignment')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: barstart')
    write('\x1b[28C100')
    write('\x1b[7Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: time')
    write('\x1b[32C0')
    write('\x1b[9Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: user')
    write('\x1b[32C0')
    write('\x1b[9Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: window')
    write('\x1b[30C0')
    write('\x1b[9Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: window_empty')
    write('\x1b[24C0')
    write('\x1b[9Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: lag')
    write('\x1b[33C-1')
    write('\x1b[8Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: act')
    write('\x1b[33C10')
    write('\x1b[8Cleft')
    write('\n')
    flush(1)
    write('12:36')
    write('\x1b[10C: more')
    write('\x1b[32C-1')
    write('\x1b[8Cright')
    write('\n')
    write('12:36')
    write('\x1b[10C: barend')
    write('\x1b[30C100')
    write('\x1b[7Cright')
    write('\n')
    write('12:36:00 [lookandfeel]')
    write('\n')
    write('12:36:00 timestamp_format =')
    write('\x1b[C%H:%M:00')
    write('\n')
    write('12:36:41 [lookandfeel]')
    write('\n')
    write('12:36:41 timestamp_format =')
    write('\x1b[C%H:%M:%S')
    write('\n')
    write(' [12:36:56] [duhowett(+i)] [1:localhost (change with ^X)]')
    write('\n')
    write('[(status)]')
    # write('\x1b]0;\x07')
    # write('\x1b]0;irssi\x07')
    write('\n')
    write('')
    write('\x1b[A [12:36:57]')
    write('\n')
    write('')
    write('\x1b[?12l')
    write('\n')
    write('')
    write('\x1b[A [12:36:58]')
    write('\n')
    write('')
    write('\x1b[?12l')
    write('\n')
    write('')
    write('\x1b[A [12:36:59]')
    write('\n')
    write('')
    write('\x1b[?12l/')
    write('\x1b[K')
    write('\n')
    write('')
    write('\x1b[A [12:37:00]')
    write('\x1b[C')
    write('\n')
    write('')
    flush(1)
    write('\x1b[?12lw')
    flush(.25)
    write('\x1b[Kh')
    flush(.25)
    write('\x1b[Ko')
    flush(.25)
    write('\x1b[Ki')
    flush(.25)
    write('\x1b[Ks')
    flush(.5)
    write('\x1b[K ')
    write('\x1b[K')
    write('\n')
    write('')
    write('\x1b[A [12:37:01]')
    write('\x1b[7C')
    write('\n')
    write('')
    write('\x1b[?12ld')
    write('\x1b[Ku')
    write('\x1b[Kh')
    write('\x1b[K')
    write('\n')
    write('')
    write('\x1b[A [12:37:02]')
    write('\x1b[10C')
    write('\n')
    write('')
    flush(1)
    write('\x1b[?12lo')
    write('\x1b[Kw')
    write('\x1b[Ke')
    write('\x1b[Kt')
    write('\x1b[Kt')
    write('\x1b[K')
    write('\x1b[15D')
    write('\x1b[K')
    write('\x1b[?12l')
    write('\x1b[H')
    write('\n')
    flush(1)
    write('')
    write('\x1b[26B')
    write('\x1b[2;28r')
    write('\x1b[28;1H')
    write('\n')
    write('')
    write('\x1b[H')
    write('\x1b[30;12H')
    write('\n')
    write('')
    flush(1)
    write('\x1b[2A12:37:02 -!- duhowett [~duhowett@97.126.91.54]')
    write('\x1b[K')
    write('\x1b[H')
    write('\n')
    write('')
    write('\x1b[26B')
    write('\n')
    write('')
    flush(1)
    write('\x1b[H')
    write('\x1b[28;47H')
    write('\n')
    write('12:37:02 -!-  ircname  : ""')
    write('\x1b[K')
    write('\x1b[H')
    write('\n')
    write('')
    write('\x1b[26B')
    write('\n')
    write('')
    write('\x1b[H')
    write('\x1b[28;28H')
    write('\n')
    flush(1)
    write('12:37:02 -!-  hostname : ~duhowett@97.126.91.54 97.126.91.54 ')
    write('\x1b[K')
    write('\x1b[H')
    write('\n')
    write('')
    write('\x1b[26B')
    write('\n')
    write('')
    write('\x1b[H')
    write('\x1b[28;62H')
    write('\n')
    flush(1)
    write('12:37:02 -!-  server   : *.irc.saurik.com [Saurik]')
    write('\x1b[K')
    write('\x1b[H')
    write('\n')
    write('')
    write('\x1b[26B')
    write('\n')
    write('')
    write('\x1b[H')
    write('\x1b[28;51H')
    write('\n')
    flush(1)
    write('12:37:02 -!- End of WHOIS')
    write('\x1b[K')
    write('\x1b[30;12H')
    write('\x1b[?12l')
    write('\n')
    write('')
    write('\x1b[A [12:37:03]')
    write('\n')

