import sys
import time # time.sleep is in seconds
from common import *

# $ python ~/vttests/name-of-file.py
if __name__ == '__main__':
    clear_all()
    print('This is the VT Test template.')
    sgr(7)
    write("This is the titlebar - should be reversed")
    csi('K')
    write('\n')
    flush(1)
    sgr(27)
    write('This is some text ')
    esc('7') # push the cursor
    write('of the body of the file')
    write('\n')
    write('\n')
    print('')
    flush(1)
    sgr_n([48, 5, 250])
    print('This is the footer')
    sgr_n([39, 49])
    esc('8')
    flush(1)
    write('This text should be normal colored')

    flush(1)
    cup(10, 1)
    sgr(0)
    print('Default Text')
    flush(.75)
    sgr(7)
    print('reverse')
    flush(.75)
    sgr(31)
    print('red foreground')
    flush(.75)
    sgr(27)
    print('reset')
    flush(.75)
    sgr(0)
    print('default')
    flush(.75)
    sgr_n([48, 5, 250])
    print('bg=250')
    flush(.75)
    sgr(39)
    print('this should be unchanged')
    flush(.75)
    sgr(49)
    print('default?')

    flush(5)
