@rem opencon - launch the openconsole binary.
@rem Runs the OpenConsole.exe binary generated by the build in the debug directory.
@rem    Passes any args along.

@setlocal
@rem This should be unique enough... random short, and the date/timestamp
@set copy_name=%random%%DATE:/=%%TIME::=%_Openconsole.exe
@rem Need to remove the space from the datestamp
@set copy_name=%copy_name: =% 

@copy /Y %OPENCON%\bin\%ARCH%\Debug\OpenConsole.exe %TEMP%\%copy_name% > nul

@rem @start %OPENCON%\bin\%ARCH%\Debug\OpenConsole.exe %* &
@start %TEMP%\%copy_name% %* &