@rem opencon - launch the openconsole binary.
@rem Runs the OpenConsole.exe binary generated by the build in the debug directory.
@rem    Passes any args along.

@start %~dp0\..\bin\x64\Debug\OpenConsole.exe %* &